/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;
import Clases.DatosGraficos;
import Clases.PintarDibujos;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author Allan
 */
public class Mapa extends javax.swing.JFrame {
    
    private int Numerotope = 0;//Numero de nodos 
    
    DatosGraficos arboles = new DatosGraficos();

    public static void PintarFiguras(int tope, DatosGraficos arboles) {//pinta lo q esta antes en el panel 
        for (int j = 0; j < tope; j++) {
            for (int k = 0; k < tope; k++) {
                if (arboles.getmAdyacencia(j, k) == 1) {
                    PintarDibujos.pinta_Linea(jLabel1.getGraphics(), arboles.getCordeX(j), arboles.getCordeY(j), arboles.getCordeX(k), arboles.getCordeY(k), arboles.getmCoeficiente(j, k));
                }
            }
        }
        for (int j = 0; j < tope; j++) {
            PintarDibujos.pinta_Circulo(jLabel1.getGraphics(), arboles.getCordeX(j), arboles.getCordeY(j), arboles.getNombre(j));
        }
    }

    /**
     * Creates new form Mapa
     */
    public Mapa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setPreferredSize(new java.awt.Dimension(1260, 670));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mapaCartago.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jButton1.setText("Mapa");
        jButton1.setActionCommand("btnVerCaminos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1126, 1126, 1126)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabel1.paint(jLabel1.getGraphics());
       
        int Matriz[][] = {
            {0, 1, 0, 1, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0},
            {1, 0, 1, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0},
            {0, 1, 0, 0, 0, 1, 0, 0, 0,  0,  0,  0,  0,  1,  0},
            {1, 0, 0, 0, 1, 1, 0, 0, 0,  0,  0,  0,  0,  0,  0},
            {0, 0, 0, 1, 0, 1, 1, 1, 0,  0,  0,  0,  0,  0,  0},
            {0, 0, 1, 1, 1, 0, 1, 0, 0,  0,  0,  0,  0,  1,  0},
            {0, 0, 0, 0, 1, 1, 0, 1, 1,  1,  0,  0,  0,  0,  0},
            {0, 0, 0, 0, 1, 0, 1, 0, 0,  0,  0,  1,  0,  0,  0},
            {0, 0, 0, 0, 0, 0, 1, 0, 0,  1,  0,  0,  1,  1,  0},
            {0, 0, 0, 0, 0, 0, 1, 0, 1,  0,  1,  0,  1,  0,  0},
            {0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  1,  0,  0,  0,  0},
            {0, 0, 0, 0, 0, 0, 0, 1, 0,  0,  1,  0,  1,  0,  1},
            {0, 0, 0, 0, 0, 0, 0, 0, 1,  1,  0,  1,  0,  1,  0},
            {0, 0, 1, 0, 0, 1, 0, 0, 1,  0,  0,  0,  1,  0,  0},
            {0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  1,  0,  0,  0}
        };

        double coe[][] = {
            {0, 11.8, 0, 24.7, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0},
            {11.8, 0, 12.1, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0},
            {0, 12.1, 0, 0, 0, 7.7, 0, 0, 0,  0,  0,  0,  0,  17.1,  0},
            {24.7, 0, 0, 0, 17.5, 23.9, 0, 0, 0,  0,  0,  0,  0,  0,  0},
            {0, 0, 0, 17.5, 0, 10.4, 11.2, 11.4, 0,  0,  0,  0,  0,  0,  0},
            {0, 0, 7.7, 23.9, 10.4, 0, 4.7, 0, 0,  0,  0,  0,  0,  17.7,  0},
            {0, 0, 0, 0, 11.2, 4.7, 0, 9.5, 6.2,  6.6,  0,  0,  0,  0,  0},
            {0, 0, 0, 0, 11.4, 0, 9.5, 0, 0,  0,  0,  20.1,  0,  0,  0},
            {0, 0, 0, 0, 0, 0, 6.2, 0, 0,  1.9,  0,  0,  13.9,  7.7,  0},
            {0, 0, 0, 0, 0, 0, 6.6, 0, 1.9,  0,  2.8,  0,  13.1,  0,  0},
            {0, 0, 0, 0, 0, 0, 0, 0, 0,  2.8,  3.3,  0,  0,  0,  0},
            {0, 0, 0, 0, 0, 0, 0, 20.1, 0,  0,  3.3,  0,  13.4,  0,  1.5},
            {0, 0, 0, 0, 0, 0, 0, 0, 13.9,  13.1,  0,  13.4,  0,  16.6,  0},
            {0, 0, 17.1, 0, 0, 17.7, 0, 0, 7.7,  0,  0,  0,  16.6,  0,  0},
            {0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  1.5,  0,  0,  0},};

          int xx1[] = {890, 710, 570, 800, 570, 480, 400, 470, 330, 235, 280, 200, 60, 350, 190};
          int yy1[] = {95, 135, 170, 300, 370, 260, 280, 480, 220, 240, 290, 280, 135, 85, 340};
        String nom[] = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"};
      
        for (int j = 0; j < 15; j++) {
            arboles.setCordeX(j, xx1[j]);
            arboles.setCordeY(j, yy1[j]);
            arboles.setNombre(j, nom[j]);

        }
        for (int j = 0; j < 15; j++) {
            for (int k = 0; k < 15; k++) {
                arboles.setmAdyacencia(j, k, Matriz[j][k]);
                arboles.setmCoeficiente(j, k, coe[j][k]);
            }
        }
        Numerotope = 15;
        PintarFiguras(Numerotope, arboles); 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mapa().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}