/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;
import Clases.AlgoritmoDijkstra;
import Clases.DatosGraficos;
import Clases.Dibujos;
import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Allan
 */
public class Mapa extends javax.swing.JFrame {
    
    private int NumVertices = 0;//Numero de nodos o vertices (lugares) 
    
    DatosGraficos datosGraficos = new DatosGraficos();

    /**
     * Creates new form Mapa
     */
    public Mapa() {
        initComponents();
        cbxDestino.setEnabled(false);
        cbxSalida.setEnabled(false);
        TrzarRuta.setEnabled(false);
        cbxRetrasos.setEnabled(false);
        jPTiempos.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        LabelMapa = new javax.swing.JLabel();
        cbxSalida = new javax.swing.JComboBox<>();
        cbxDestino = new javax.swing.JComboBox<>();
        TrzarRuta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxRetrasos = new javax.swing.JComboBox<>();
        jPTiempos = new javax.swing.JPanel();
        txtTestimado = new javax.swing.JTextField();
        tituloConretraso = new javax.swing.JLabel();
        txtTiempo = new javax.swing.JTextField();
        tituloSinretraso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        jButton1.setBackground(new java.awt.Color(5, 22, 4));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Mapa");
        jButton1.setActionCommand("btnVerCaminos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        LabelMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mapaCartago.jpg"))); // NOI18N
        LabelMapa.setText("jLabel1");

        cbxSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Turrialba", "Juan Viñas", "Cervantes", "Tucurrique", "Cachi", "Birrisito", "Paraiso", "Orosi", "Oreamuno", "Cartago", "Pitahaya", "El Tejar", "Tres Rios", "Tierra Blanca", "La Fundacion" }));
        cbxSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSalidaActionPerformed(evt);
            }
        });

        cbxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Turrialba", "Juan Viñas", "Cervantes", "Tucurrique", "Cachi", "Birrisito", "Paraiso", "Orosi", "Oreamuno", "Cartago", "Pitahaya", "El Tejar", "Tres Rios", "Tierra Blanca", "La Fundacion" }));
        cbxDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDestinoActionPerformed(evt);
            }
        });

        TrzarRuta.setText("Ir");
        TrzarRuta.setActionCommand("btnBuscarRuta");
        TrzarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrzarRutaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Lugar de Origen");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Lugar de Destino");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Retrasos");

        cbxRetrasos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presa", "Semaforo", "Choque", "Accidente", "Animales en la carretera", "Derrumbe" }));

        jPTiempos.setBackground(new java.awt.Color(102, 102, 102));

        txtTestimado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTestimado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTestimado.setText("0");

        tituloConretraso.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tituloConretraso.setText("Tiempo estimado");

        txtTiempo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTiempo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTiempo.setText("0");
        txtTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiempoActionPerformed(evt);
            }
        });

        tituloSinretraso.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tituloSinretraso.setText("Tiempo sin retrasos");

        javax.swing.GroupLayout jPTiemposLayout = new javax.swing.GroupLayout(jPTiempos);
        jPTiempos.setLayout(jPTiemposLayout);
        jPTiemposLayout.setHorizontalGroup(
            jPTiemposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTiemposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPTiemposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTestimado, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloConretraso)
                    .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloSinretraso))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPTiemposLayout.setVerticalGroup(
            jPTiemposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTiemposLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(tituloSinretraso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloConretraso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTestimado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 947, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(cbxSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxRetrasos, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(83, 83, 83)
                            .addComponent(TrzarRuta)))
                    .addComponent(jPTiempos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxRetrasos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TrzarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPTiempos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LabelMapa.paint(LabelMapa.getGraphics());
        cbxSalida.setEnabled(true);
       
        int MatrizAdyacencia[][] = {
            {0, 1, 0, 1, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0}, // 1
            {1, 0, 1, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0}, // 2
            {0, 1, 0, 0, 0, 1, 0, 0, 0,  0,  0,  0,  0,  1,  0}, // 3
            {1, 0, 0, 0, 1, 1, 0, 0, 0,  0,  0,  0,  0,  0,  0}, // 4
            {0, 0, 0, 1, 0, 1, 1, 1, 0,  0,  0,  0,  0,  0,  0}, // 5
            {0, 0, 1, 1, 1, 0, 1, 0, 0,  0,  0,  0,  0,  1,  0}, // 6
            {0, 0, 0, 0, 1, 1, 0, 1, 1,  1,  0,  0,  0,  0,  0}, // 7
            {0, 0, 0, 0, 1, 0, 1, 0, 0,  0,  0,  1,  0,  0,  0}, // 8
            {0, 0, 0, 0, 0, 0, 1, 0, 0,  1,  0,  0,  1,  1,  0}, // 9
            {0, 0, 0, 0, 0, 0, 1, 0, 1,  0,  1,  0,  1,  0,  0}, // 10
            {0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  0,  1,  0,  0,  0}, // 11
            {0, 0, 0, 0, 0, 0, 0, 1, 0,  0,  1,  0,  1,  0,  1}, // 12
            {0, 0, 0, 0, 0, 0, 0, 0, 1,  1,  0,  1,  0,  1,  0}, // 13
            {0, 0, 1, 0, 0, 1, 0, 0, 1,  0,  0,  0,  1,  0,  0}, // 14
            {0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  1,  0,  0,  0}  // 15
        };

        double distancias[][] = {
            {0, 8.9, 0, 18.5, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0},
            {8.9, 0, 9.2, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0},
            {0, 9.2, 0, 0, 0, 5.8, 0, 0, 0,  0,  0,  0,  0,  12.8,  0},
            {18.5, 0, 0, 0, 13.1, 17.9, 0, 0, 0,  0,  0,  0,  0,  0,  0},
            {0, 0, 0, 13.1, 0, 7.8, 8.4, 8.6, 0,  0,  0,  0,  0,  0,  0},
            {0, 0, 5.8, 17.9, 7.8, 0, 3.5, 0, 0,  0,  0,  0,  0,  13.3,  0},
            {0, 0, 0, 0, 8.4, 3.5, 0, 7.1, 4.7,  5,  0,  0,  0,  0,  0},
            {0, 0, 0, 0, 8.6, 0, 7.1, 0, 0,  0,  0,  15.1,  0,  0,  0},
            {0, 0, 0, 0, 0, 0, 4.7, 0, 0,  1.4,  0,  0,  10.4,  5.8,  0},
            {0, 0, 0, 0, 0, 0, 5, 0, 1.4,  0,  2.1,  0,  10,  0,  0},
            {0, 0, 0, 0, 0, 0, 0, 0, 0,  2.1,  0,  2.5,  0,  0,  0},
            {0, 0, 0, 0, 0, 0, 0, 15.1, 0,  0,  2.5,  0,  10.1,  0,  1.2},
            {0, 0, 0, 0, 0, 0, 0, 0, 10.4,  9.8,  0,  10.1,  0,  12.5,  0},
            {0, 0, 12.8, 0, 0, 13.3, 0, 0, 5.8,  0,  0,  0,  12.5,  0,  0},
            {0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  1.2,  0,  0,  0}};         // 15

        int coordenadasX[] = {890, 710, 570, 800, 570, 480, 400, 470, 320, 235, 280,  200,  60,  350,  190};
        int coordenadasY[] = {95,  135, 170, 300, 370, 260, 280, 480, 215, 240, 290,  280,  135,  85,  335};
             String nom[] =  {"Turrialba", "Juan Viñas", "Cervantes", "Tucurrique", "Cachí", "Birrisito", "Paraiso", "Orosi", "Oreamuno", "Cartago", "Pitahaya", "Tejar", "Tres Ríos", "Tierra Blanca", "La Fundacion"};
      
        for (int j = 0; j < 15; j++) {
            datosGraficos.setCoordeX(j, coordenadasX[j]);
            datosGraficos.setCoordeY(j, coordenadasY[j]);
            datosGraficos.setNombre(j, nom[j]);

        }
        for (int j = 0; j < 15; j++) {
            for (int k = 0; k < 15; k++) {
                datosGraficos.setmAdyacencia(j, k, MatrizAdyacencia[j][k]);
                datosGraficos.setmDistancias(j, k, distancias[j][k]);
            }
        }
        NumVertices = 15;
        try { 
            PintarRutas(NumVertices, datosGraficos);
        } catch (IOException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

        // Dibuja lineas que representan las rutas posibles que el usuario puede escoger
    public static void PintarRutas(int numVertices, DatosGraficos arboles) throws IOException {// pinta todas las rutas en el mapa a escoger
        for (int j = 0; j < numVertices; j++) {
            for (int k = 0; k < numVertices; k++) {
                if (arboles.getmAdyacencia(j, k) == 1) { //se pinta las líneas
                    Dibujos.pinta_Rutas(LabelMapa.getGraphics(), arboles.getCoordeX(j), arboles.getCoordeY(j), arboles.getCoordeX(k), arboles.getCoordeY(k), arboles.getmDistancias(j, k));
                }
            }
        }
        for (int j = 0; j < numVertices; j++) { // se pintan los simbolos de ubicación en cada lugar
            Dibujos.pinta_localizador(LabelMapa.getGraphics(), arboles.getCoordeX(j), arboles.getCoordeY(j), arboles.getNombre(j));
            
        }
    }
    
    /**
     * odigo par atrazar la ruta seleccionada, cone l boton btnbuscar
     * @param evt 
     */
    private void TrzarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrzarRutaActionPerformed

        int origen = 0, destino = 0, retrasos = 0;
        String nombreOrigen, nombreDestino, nombreRetrasos;
        nombreOrigen = (String) cbxSalida.getSelectedItem();
        nombreDestino = (String) cbxDestino.getSelectedItem();
        nombreRetrasos = (String) cbxRetrasos.getSelectedItem();
        
        
        if ("Turrialba".equals(nombreOrigen)) {
            origen = 0;
        }
        if ("Juan Viñas".equals(nombreOrigen)) {
            origen = 1;
        }
        if ("Cervantes".equals(nombreOrigen)) {
            origen = 2;
        }
        if ("Tucurrique".equals(nombreOrigen)) {
            origen = 3;
        }
        if ("Cachi".equals(nombreOrigen)) {
            origen = 4;
        }
        if ("Birrisito".equals(nombreOrigen)) {
            origen = 5;
        }
        if ("Paraiso".equals(nombreOrigen)) {
            origen = 6;
        }
        if ("Orosi".equals(nombreOrigen)) {
            origen = 7;
        }
        if ("Oreamuno".equals(nombreOrigen)) {
            origen = 8;
        }
        if ("Cartago".equals(nombreOrigen)) {
            origen = 9;
        }
        if ("Pitahaya".equals(nombreOrigen)) {
            origen = 10;
        }
        if ("El Tejar".equals(nombreOrigen)) {
            origen = 11;
        }
        if ("Tres Rios".equals(nombreOrigen)) {
            origen = 12;
        }
        if ("Tierra Blanca".equals(nombreOrigen)) {
            origen = 13;
        }
        if ("La Fundacion".equals(nombreOrigen)) {
            origen = 14;
        }
 
        /*************************************/
        
        
        if ("Turrialba".equals(nombreDestino)) {
            destino = 0;
        }
        if ("Juan Viñas".equals(nombreDestino)) {
            destino = 1;
        }
        if ("Cervantes".equals(nombreDestino)) {
            destino = 2;
        }
        if ("Tucurrique".equals(nombreDestino)) {
            destino = 3;
        }
        if ("Cachi".equals(nombreDestino)) {
            destino = 4;
        }
        if ("Birrisito".equals(nombreDestino)) {
            destino = 5;
        }
        if ("Paraiso".equals(nombreDestino)) {
            destino = 6;
        }
        if ("Orosi".equals(nombreDestino)) {
            destino = 7;
        }
        if ("Oreamuno".equals(nombreDestino)) {
            destino = 8;
        }
        if ("Cartago".equals(nombreDestino)) {
            destino = 9;
        }
        if ("Pitahaya".equals(nombreDestino)) {
            destino = 10;
        }
        if ("El Tejar".equals(nombreDestino)) {
            destino = 11;
        }
        if ("Tres Rios".equals(nombreDestino)) {
            destino = 12;
        }
        if ("Tierra Blanca".equals(nombreDestino)) {
            destino = 13;
        }
        if ("La Fundacion".equals(nombreDestino)) {
            destino = 14;
        }
        //Presa, Semaforo, Choque, Accidente, Animales en la carretera, Derrumbe
        if ("Presa".equals(nombreRetrasos)) {
            retrasos = 15;
        }
        if ("Semaforo".equals(nombreRetrasos)) {
            retrasos = 3;
        }
        if ("Choque".equals(nombreRetrasos)) {
            retrasos = 20;
        }
        if ("Accidente".equals(nombreRetrasos)) {
            retrasos = 40;
        }
        if ("Animales en la carretera".equals(nombreRetrasos)) {
            retrasos = 10;
        }
        if ("Derrumbe".equals(nombreRetrasos)) {
            retrasos = 25;
        }
        
        //Se hacen visibles los camos
        jPTiempos.setVisible(true);
        
        if (origen == destino) {
            Font fuente = new Font("Arial", Font.BOLD, 18);
            //txtKMAcumulados.setFont(fuente);
            JOptionPane.showMessageDialog(null, "Estás en:" + nombreOrigen+"!");
            //txtKMAcumulados.setText("Intenta de nuevo!!");
            //txtKMAcumulados.setEnabled(false);
            //txtKMAcumulados.setForeground(Color.RED);

        } else {
            AlgoritmoDijkstra Dijkstra = new AlgoritmoDijkstra(datosGraficos, NumVertices, origen, destino);
            try {
                Dijkstra.dijkstra();
            } catch (IOException ex) {
                Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
            }

            Font fuente = new Font("Arial", Font.BOLD, 18);
     
            txtTiempo.setText(Dijkstra.getAcumulado() + " MIN");
            txtTestimado.setText( Dijkstra.getAcumulado()+ retrasos+ " MIN");
        }
        
    }//GEN-LAST:event_TrzarRutaActionPerformed

    private void cbxSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSalidaActionPerformed
        cbxDestino.setEnabled(true);
    }//GEN-LAST:event_cbxSalidaActionPerformed

    private void cbxDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDestinoActionPerformed
        TrzarRuta.setEnabled(true);
        cbxRetrasos.setEnabled(true);
    }//GEN-LAST:event_cbxDestinoActionPerformed

    private void txtTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiempoActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mapa().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel LabelMapa;
    private javax.swing.JButton TrzarRuta;
    private javax.swing.JComboBox<String> cbxDestino;
    public javax.swing.JComboBox<String> cbxRetrasos;
    private javax.swing.JComboBox<String> cbxSalida;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JPanel jPTiempos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tituloConretraso;
    private javax.swing.JLabel tituloSinretraso;
    public javax.swing.JTextField txtTestimado;
    public javax.swing.JTextField txtTiempo;
    // End of variables declaration//GEN-END:variables
}