
package VENTANAS;
import Clases.AlgoritmoDijkstra;
import Clases.DatosGraficos;
import Clases.Dibujos;
import Clases.LeeMatriz;
import java.awt.Font;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/***
 *Esta clase contiene la interfaz del mapa y las clases necesarias para desplegar las rutas
 * @author Allan Prieto, Allan Chen, Valerin Calderon, Daniel Rayo, Ludwin Ramos
 * @since 25/11/2021
 * @version 1.0
 */
public class Mapa extends javax.swing.JFrame {
    
    private int NumVertices = 0;//Numero de nodos o vertices (lugares) 
    
    DatosGraficos datosGraficos = new DatosGraficos(); // objeto de la clase "DatosGraficos"

    /**
     * Inicializa los componentes
     */
    public Mapa() {
        initComponents();
        this.setLocationRelativeTo(null);
        cbxDestino.setEnabled(false);
        cbxSalida.setEnabled(false);
        TrzarRuta.setEnabled(false);
        cbxRetrasos.setEnabled(false);
        jPTiempos.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonMostrar = new javax.swing.JButton();
        LabelMapa = new javax.swing.JLabel();
        TrzarRuta = new javax.swing.JButton();
        jPTiempos = new javax.swing.JPanel();
        tituloConretraso = new javax.swing.JLabel();
        tituloSinretraso = new javax.swing.JLabel();
        txtTiempo = new javax.swing.JLabel();
        txtTestimado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxSalida = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbxDestino = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbxRetrasos = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        ButtonMostrar.setBackground(new java.awt.Color(153, 153, 153));
        ButtonMostrar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ButtonMostrar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/imgMapa.png"))); // NOI18N
        ButtonMostrar.setActionCommand("btnVerCaminos");
        ButtonMostrar.setBorder(null);
        ButtonMostrar.setBorderPainted(false);
        ButtonMostrar.setContentAreaFilled(false);
        ButtonMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonMostrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/imgMapaBuscar.png"))); // NOI18N
        ButtonMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonMostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonMostrarMouseExited(evt);
            }
        });
        ButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMostrarActionPerformed(evt);
            }
        });

        LabelMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mapaCartago.jpg"))); // NOI18N
        LabelMapa.setText("jLabel1");
        LabelMapa.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 51, 51)));
        LabelMapa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        TrzarRuta.setBackground(new java.awt.Color(153, 153, 153));
        TrzarRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/imgLupaPequeña.png"))); // NOI18N
        TrzarRuta.setActionCommand("btnBuscarRuta");
        TrzarRuta.setContentAreaFilled(false);
        TrzarRuta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TrzarRuta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/imgLupa.png"))); // NOI18N
        TrzarRuta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TrzarRutaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TrzarRutaMouseExited(evt);
            }
        });
        TrzarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrzarRutaActionPerformed(evt);
            }
        });

        jPTiempos.setBackground(new java.awt.Color(72, 129, 129));

        tituloConretraso.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tituloConretraso.setText("Tiempo estimado");

        tituloSinretraso.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tituloSinretraso.setText("Tiempo sin retrasos");

        txtTiempo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTiempo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtTiempo.setOpaque(true);

        txtTestimado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTestimado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtTestimado.setOpaque(true);

        javax.swing.GroupLayout jPTiemposLayout = new javax.swing.GroupLayout(jPTiempos);
        jPTiempos.setLayout(jPTiemposLayout);
        jPTiemposLayout.setHorizontalGroup(
            jPTiemposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTiemposLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloConretraso)
                .addGap(66, 66, 66))
            .addGroup(jPTiemposLayout.createSequentialGroup()
                .addGroup(jPTiemposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTiemposLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(tituloSinretraso))
                    .addGroup(jPTiemposLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPTiemposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTestimado, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPTiemposLayout.setVerticalGroup(
            jPTiemposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTiemposLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(tituloSinretraso)
                .addGap(11, 11, 11)
                .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloConretraso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTestimado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel2.setBackground(new java.awt.Color(71, 141, 141));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Lugar de Origen");

        cbxSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Turrialba", "Juan Viñas", "Cervantes", "Tucurrique", "Cachi", "Birrisito", "Paraiso", "Orosi", "Oreamuno", "Cartago", "Pitahaya", "El Tejar", "Tres Rios", "Tierra Blanca", "La Fundacion" }));
        cbxSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSalidaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Lugar de Destino");

        cbxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Turrialba", "Juan Viñas", "Cervantes", "Tucurrique", "Cachi", "Birrisito", "Paraiso", "Orosi", "Oreamuno", "Cartago", "Pitahaya", "El Tejar", "Tres Rios", "Tierra Blanca", "La Fundacion" }));
        cbxDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDestinoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Retrasos");

        cbxRetrasos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presa", "Semaforo", "Choque", "Accidente", "Animales en la carretera", "Derrumbe" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cbxSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbxRetrasos, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxRetrasos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 947, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPTiempos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(TrzarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(52, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TrzarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPTiempos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelMapa)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMostrarActionPerformed
        try {                                              
            LabelMapa.paint(LabelMapa.getGraphics());
            cbxSalida.setEnabled(true);
            int MatrizAdyacencia[][];
            // matriz que posee las conexiones directas que existen entre los vértices o lugares del mapa.
            LeeMatriz leerMatrizAdyacencia = new LeeMatriz("MatrizAdyacencia.txt");
            MatrizAdyacencia= leerMatrizAdyacencia.get_matrizAdyacencia();

            // matriz que posee los costos o pesos que existen entre los vértices o lugares del mapa.
            LeeMatriz leerMatrizCostos = new LeeMatriz("MatrizCostos.txt");
            double costos[][] = leerMatrizCostos.get_matrizCostos();
            
            // coordenafas de cada vértice en el mapa
            int coordenadasX[] = {890, 710, 570, 800, 570, 480, 400, 470, 320, 235, 280,  200,  60,  350,  190};
            int coordenadasY[] = {95,  135, 170, 300, 370, 260, 280, 480, 215, 240, 290,  280,  135,  85,  335};
            String nom[] =  {"Turrialba", "Juan Viñas", "Cervantes", "Tucurrique", "Cachí", "Birrisito", "Paraiso", "Orosi", "Oreamuno", "Cartago", "Pitahaya", "Tejar", "Tres Ríos", "Tierra Blanca", "La Fundacion"};
            
            for (int j = 0; j < 15; j++) {
                datosGraficos.setCoordeX(j, coordenadasX[j]);
                datosGraficos.setCoordeY(j, coordenadasY[j]);
                datosGraficos.setNombre(j, nom[j]);
                
            }
            for (int j = 0; j < 15; j++) {
                for (int k = 0; k < 15; k++) {
                    datosGraficos.setmAdyacencia(j, k, MatrizAdyacencia[j][k]);
                    datosGraficos.setmDistancias(j, k, costos[j][k]);
                }
            }
            NumVertices = 15;
            try {
                PintarRutas(NumVertices, datosGraficos);
            } catch (IOException ex) {
                Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonMostrarActionPerformed
 
    /**
     * Metodo para pintar las rutas y el ícono de localización.
     * @param numVertices número de vértices
     * @param datosgraficos objeto de la clase "DatosGraficos"
     * @throws IOException 
     */
    public static void PintarRutas(int numVertices, DatosGraficos datosgraficos) throws IOException {// pinta todas las rutas en el mapa a escoger
        for (int j = 0; j < numVertices; j++) {
            for (int k = 0; k < numVertices; k++) {
                if (datosgraficos.getmAdyacencia(j, k) == 1) { //se pinta las líneas
                    Dibujos.pinta_Rutas(LabelMapa.getGraphics(), datosgraficos.getCoordeX(j), datosgraficos.getCoordeY(j), datosgraficos.getCoordeX(k), datosgraficos.getCoordeY(k), datosgraficos.getmDistancias(j, k));
                }
            }
        }
        for (int j = 0; j < numVertices; j++) { // se pintan los simbolos de ubicación en cada lugar
            Dibujos.pinta_localizador(LabelMapa.getGraphics(), datosgraficos.getCoordeX(j), datosgraficos.getCoordeY(j), datosgraficos.getNombre(j));
            
        }
    }
    
    
    //métddo para trazar la ruta seleccionada, del boton TrazarRuta
     
    private void TrzarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrzarRutaActionPerformed

        int origen = 0, destino = 0, retrasos = 0;
        String nombreOrigen, nombreDestino, nombreRetrasos;
        nombreOrigen = (String) cbxSalida.getSelectedItem();
        nombreDestino = (String) cbxDestino.getSelectedItem();
        nombreRetrasos = (String) cbxRetrasos.getSelectedItem();
        
        
        if ("Turrialba".equals(nombreOrigen)) {
            origen = 0;
        }
        if ("Juan Viñas".equals(nombreOrigen)) {
            origen = 1;
        }
        if ("Cervantes".equals(nombreOrigen)) {
            origen = 2;
        }
        if ("Tucurrique".equals(nombreOrigen)) {
            origen = 3;
        }
        if ("Cachi".equals(nombreOrigen)) {
            origen = 4;
        }
        if ("Birrisito".equals(nombreOrigen)) {
            origen = 5;
        }
        if ("Paraiso".equals(nombreOrigen)) {
            origen = 6;
        }
        if ("Orosi".equals(nombreOrigen)) {
            origen = 7;
        }
        if ("Oreamuno".equals(nombreOrigen)) {
            origen = 8;
        }
        if ("Cartago".equals(nombreOrigen)) {
            origen = 9;
        }
        if ("Pitahaya".equals(nombreOrigen)) {
            origen = 10;
        }
        if ("El Tejar".equals(nombreOrigen)) {
            origen = 11;
        }
        if ("Tres Rios".equals(nombreOrigen)) {
            origen = 12;
        }
        if ("Tierra Blanca".equals(nombreOrigen)) {
            origen = 13;
        }
        if ("La Fundacion".equals(nombreOrigen)) {
            origen = 14;
        }
 
        /*************************************/
        
        
        if ("Turrialba".equals(nombreDestino)) {
            destino = 0;
        }
        if ("Juan Viñas".equals(nombreDestino)) {
            destino = 1;
        }
        if ("Cervantes".equals(nombreDestino)) {
            destino = 2;
        }
        if ("Tucurrique".equals(nombreDestino)) {
            destino = 3;
        }
        if ("Cachi".equals(nombreDestino)) {
            destino = 4;
        }
        if ("Birrisito".equals(nombreDestino)) {
            destino = 5;
        }
        if ("Paraiso".equals(nombreDestino)) {
            destino = 6;
        }
        if ("Orosi".equals(nombreDestino)) {
            destino = 7;
        }
        if ("Oreamuno".equals(nombreDestino)) {
            destino = 8;
        }
        if ("Cartago".equals(nombreDestino)) {
            destino = 9;
        }
        if ("Pitahaya".equals(nombreDestino)) {
            destino = 10;
        }
        if ("El Tejar".equals(nombreDestino)) {
            destino = 11;
        }
        if ("Tres Rios".equals(nombreDestino)) {
            destino = 12;
        }
        if ("Tierra Blanca".equals(nombreDestino)) {
            destino = 13;
        }
        if ("La Fundacion".equals(nombreDestino)) {
            destino = 14;
        }
        //Presa, Semaforo, Choque, Accidente, Animales en la carretera, Derrumbe
        //combobox de tiempo de retrasos
        if ("Presa".equals(nombreRetrasos)) {
            retrasos = 15;
        }
        if ("Semaforo".equals(nombreRetrasos)) {
            retrasos = 3;
        }
        if ("Choque".equals(nombreRetrasos)) {
            retrasos = 20;
        }
        if ("Accidente".equals(nombreRetrasos)) {
            retrasos = 40;
        }
        if ("Animales en la carretera".equals(nombreRetrasos)) {
            retrasos = 10;
        }
        if ("Derrumbe".equals(nombreRetrasos)) {
            retrasos = 25;
        }
        
        //Se hacen visibles los camos
        jPTiempos.setVisible(true);
        
        if (origen == destino) {
            Font fuente = new Font("Arial", Font.BOLD, 18);
            JOptionPane.showMessageDialog(null, "Estás en:" + nombreOrigen+"!");
            
            jPTiempos.setVisible(false);


        } else {
            AlgoritmoDijkstra Dijkstra = new AlgoritmoDijkstra(datosGraficos, NumVertices, origen, destino);
            try {
                Dijkstra.dijkstra();
            } catch (IOException ex) {
                Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
            }

            Font fuente = new Font("Arial", Font.BOLD, 18);
     
            txtTiempo.setText(Dijkstra.getAcumulado() + " MIN"+" ");
            txtTestimado.setText( Dijkstra.getAcumulado()+ retrasos+ " MIN"+" ");
        }
        
    }//GEN-LAST:event_TrzarRutaActionPerformed

    private void cbxSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSalidaActionPerformed
        cbxDestino.setEnabled(true);
    }//GEN-LAST:event_cbxSalidaActionPerformed

    private void cbxDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDestinoActionPerformed
        TrzarRuta.setEnabled(true);
        cbxRetrasos.setEnabled(true);
    }//GEN-LAST:event_cbxDestinoActionPerformed

    private void ButtonMostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMostrarMouseEntered
        // TODO add your handling code here:
        ButtonMostrar.setOpaque(true);
    }//GEN-LAST:event_ButtonMostrarMouseEntered

    private void ButtonMostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMostrarMouseExited
        // TODO add your handling code here:
        ButtonMostrar.setOpaque(false);
    }//GEN-LAST:event_ButtonMostrarMouseExited

    private void TrzarRutaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrzarRutaMouseEntered
        // TODO add your handling code here:
        TrzarRuta.setOpaque(true);
    }//GEN-LAST:event_TrzarRutaMouseEntered

    private void TrzarRutaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrzarRutaMouseExited
        // TODO add your handling code here:
        TrzarRuta.setOpaque(false);
    }//GEN-LAST:event_TrzarRutaMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Interfaz h = new Interfaz ();
      h.setVisible(true);
      this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    /**
     * Método principal de la clase "Mapa"
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mapa().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonMostrar;
    public static javax.swing.JLabel LabelMapa;
    private javax.swing.JButton TrzarRuta;
    private javax.swing.JComboBox<String> cbxDestino;
    public javax.swing.JComboBox<String> cbxRetrasos;
    private javax.swing.JComboBox<String> cbxSalida;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JPanel jPTiempos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel tituloConretraso;
    private javax.swing.JLabel tituloSinretraso;
    private javax.swing.JLabel txtTestimado;
    private javax.swing.JLabel txtTiempo;
    // End of variables declaration//GEN-END:variables
}