/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VENTANAS;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import Clases.AlgoritmoDijkstra;
import Clases.DatosGraficos;
import Clases.Dibujos;
import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Valerine
 */
public class Interfaz extends javax.swing.JFrame {
    
    private int NumVertices = 0;//Numero de nodos o vertices (lugares) 
    
    DatosGraficos datosGraficos = new DatosGraficos();
    /**
     * Creates new form Interfaz2
     */
    public Interfaz() {
        initComponents();
        cbxDestino.setEnabled(false);
        cbxSalida.setEnabled(false);
        TrzarRuta.setEnabled(false);
        cbxRetrasos.setEnabled(false);
        jPTiempos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaInicial = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ButtonMostrar = new javax.swing.JButton();
        LabelMapa = new javax.swing.JLabel();
        TrzarRuta = new javax.swing.JButton();
        jPTiempos = new javax.swing.JPanel();
        tituloConretraso = new javax.swing.JLabel();
        tituloSinretraso = new javax.swing.JLabel();
        txtTiempo = new javax.swing.JLabel();
        txtTestimado = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbxSalida = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbxDestino = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbxRetrasos = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jButton21 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainForm");
        setName("MainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1250, 668));
        setResizable(false);
        setSize(new java.awt.Dimension(840, 430));

        VentanaInicial.setBackground(new java.awt.Color(255, 102, 255));
        VentanaInicial.setPreferredSize(new java.awt.Dimension(1240, 630));
        VentanaInicial.setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        VentanaInicial.add(jButton1);
        jButton1.setBounds(0, 40, 200, 40);

        jButton16.setBackground(new java.awt.Color(0, 0, 0));
        jButton16.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton16.setForeground(new java.awt.Color(204, 204, 204));
        jButton16.setText("Informacion");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        VentanaInicial.add(jButton16);
        jButton16.setBounds(0, 0, 100, 40);

        jButton17.setBackground(new java.awt.Color(0, 0, 0));
        jButton17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton17.setForeground(new java.awt.Color(204, 204, 204));
        jButton17.setText("Salir");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        VentanaInicial.add(jButton17);
        jButton17.setBounds(100, 0, 100, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Fondo (2).jpg"))); // NOI18N
        VentanaInicial.add(jLabel1);
        jLabel1.setBounds(-10, 0, 1250, 630);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1240, 630));
        jPanel1.setLayout(null);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(30, 60, 110, 30);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Birrisito");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(180, 300, 160, 40);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Cachì");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(180, 340, 160, 40);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Cartago");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(180, 380, 160, 40);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Cervantes");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(340, 300, 160, 40);

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Fundaciòn");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(340, 340, 160, 40);

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Juan Viñas");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(340, 380, 160, 40);

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Oreamuno");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(500, 300, 160, 40);

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Orosi");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(500, 340, 160, 40);

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Paraìso");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(500, 380, 160, 40);

        jButton12.setBackground(new java.awt.Color(0, 0, 0));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Pitahaya");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(660, 300, 160, 40);

        jButton13.setBackground(new java.awt.Color(0, 0, 0));
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Tejar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(660, 340, 160, 40);

        jButton14.setBackground(new java.awt.Color(0, 0, 0));
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Tierra Blanca");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(660, 380, 160, 40);

        jButton15.setBackground(new java.awt.Color(0, 0, 0));
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Tres Rios");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(820, 300, 160, 40);

        jButton18.setBackground(new java.awt.Color(0, 0, 0));
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("Tucurrique");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);
        jButton18.setBounds(820, 340, 160, 40);

        jButton19.setBackground(new java.awt.Color(0, 0, 0));
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("Turrialba");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19);
        jButton19.setBounds(820, 380, 160, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/LOGO (2) (1).png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(890, 500, 270, 110);

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Inf (3).png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 70, 960, 560);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(1268, 671));
        jPanel2.setLayout(null);

        ButtonMostrar.setBackground(new java.awt.Color(153, 153, 153));
        ButtonMostrar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ButtonMostrar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/imgMapa.png"))); // NOI18N
        ButtonMostrar.setActionCommand("btnVerCaminos");
        ButtonMostrar.setBorder(null);
        ButtonMostrar.setBorderPainted(false);
        ButtonMostrar.setContentAreaFilled(false);
        ButtonMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonMostrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/imgMapaBuscar.png"))); // NOI18N
        ButtonMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonMostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonMostrarMouseExited(evt);
            }
        });
        ButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonMostrar);
        ButtonMostrar.setBounds(25, 6, 77, 44);

        LabelMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mapaCartago.jpg"))); // NOI18N
        LabelMapa.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 51, 51)));
        LabelMapa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelMapa.setPreferredSize(new java.awt.Dimension(1105, 603));
        jPanel2.add(LabelMapa);
        LabelMapa.setBounds(10, 56, 947, 566);

        TrzarRuta.setBackground(new java.awt.Color(153, 153, 153));
        TrzarRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/imgLupaPequeña.png"))); // NOI18N
        TrzarRuta.setActionCommand("btnBuscarRuta");
        TrzarRuta.setContentAreaFilled(false);
        TrzarRuta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TrzarRuta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/imgLupa.png"))); // NOI18N
        TrzarRuta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TrzarRutaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TrzarRutaMouseExited(evt);
            }
        });
        TrzarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrzarRutaActionPerformed(evt);
            }
        });
        jPanel2.add(TrzarRuta);
        TrzarRuta.setBounds(1061, 258, 73, 56);

        jPTiempos.setBackground(new java.awt.Color(72, 129, 129));

        tituloConretraso.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tituloConretraso.setText("Tiempo estimado");

        tituloSinretraso.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tituloSinretraso.setText("Tiempo sin retrasos");

        txtTiempo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTiempo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtTiempo.setOpaque(true);

        txtTestimado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTestimado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtTestimado.setOpaque(true);

        javax.swing.GroupLayout jPTiemposLayout = new javax.swing.GroupLayout(jPTiempos);
        jPTiempos.setLayout(jPTiemposLayout);
        jPTiemposLayout.setHorizontalGroup(
            jPTiemposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTiemposLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloConretraso)
                .addGap(66, 66, 66))
            .addGroup(jPTiemposLayout.createSequentialGroup()
                .addGroup(jPTiemposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTiemposLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(tituloSinretraso))
                    .addGroup(jPTiemposLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPTiemposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTestimado, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPTiemposLayout.setVerticalGroup(
            jPTiemposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTiemposLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(tituloSinretraso)
                .addGap(11, 11, 11)
                .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloConretraso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTestimado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel2.add(jPTiempos);
        jPTiempos.setBounds(975, 325, 245, 129);

        jPanel4.setBackground(new java.awt.Color(71, 141, 141));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("Lugar de Origen");

        cbxSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Turrialba", "Juan Viñas", "Cervantes", "Tucurrique", "Cachi", "Birrisito", "Paraiso", "Orosi", "Oreamuno", "Cartago", "Pitahaya", "El Tejar", "Tres Rios", "Tierra Blanca", "La Fundacion" }));
        cbxSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSalidaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setText("Lugar de Destino");

        cbxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Turrialba", "Juan Viñas", "Cervantes", "Tucurrique", "Cachi", "Birrisito", "Paraiso", "Orosi", "Oreamuno", "Cartago", "Pitahaya", "El Tejar", "Tres Rios", "Tierra Blanca", "La Fundacion" }));
        cbxDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDestinoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setText("Retrasos");

        cbxRetrasos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presa", "Semaforo", "Choque", "Accidente", "Animales en la carretera", "Derrumbe" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cbxSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbxRetrasos, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxRetrasos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(975, 56, 253, 191);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1240, 630));
        jPanel3.setLayout(null);

        jButton21.setBackground(new java.awt.Color(0, 0, 0));
        jButton21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton21.setForeground(new java.awt.Color(204, 204, 204));
        jButton21.setText("Regresar");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton21);
        jButton21.setBounds(960, 550, 130, 50);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/LOGO (2) (1).png"))); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel3.add(jLabel4);
        jLabel4.setBounds(80, 20, 1170, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(VentanaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 1240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(VentanaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VentanaInicial.setVisible(true);
        jPanel1.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
       jPanel1.setVisible(true);
       VentanaInicial.setVisible(false);
    }//GEN-LAST:event_jButton16ActionPerformed
    // Funcion al boton de Tucurrique
    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
    ImageIcon img = new ImageIcon("Tucurrique.png");
    jLabel4.setIcon(img);
    jPanel1.setVisible(false);
    jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton18ActionPerformed
    // Funcion al boton de Juan Viñas
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    ImageIcon img = new ImageIcon("Juan Viñas.png");
    jLabel4.setIcon(img);
    jPanel1.setVisible(false);
    jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
     jPanel3.setVisible(false);
     jPanel1.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed
    // Funcion al boton de Cachi
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    ImageIcon img = new ImageIcon("Cachi (1).png");
    jLabel4.setIcon(img);
    jPanel1.setVisible(false);
    jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed
    // Funcion al boton de Birrisito
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    ImageIcon img = new ImageIcon("Birrisito (1).png");
    jLabel4.setIcon(img);
    jPanel1.setVisible(false);
    jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
    // Funcion al boton de Turrialba
    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
    ImageIcon img = new ImageIcon("Turrialba.png");
    jLabel4.setIcon(img);
    jPanel1.setVisible(false);
    jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed
    // Funcion al boton de Paraiso
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
    ImageIcon img = new ImageIcon("Paraiso (1).png");
    jLabel4.setIcon(img);
    jPanel1.setVisible(false);
    jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed
    // Funcion al boton de Orosi
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
    ImageIcon img = new ImageIcon("Orosi (1).png");
    jLabel4.setIcon(img);
    jPanel1.setVisible(false);
    jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed
    // Funcion al boton de Cartago
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    ImageIcon img = new ImageIcon("CartagoC (1).png");
    jLabel4.setIcon(img);
    jPanel1.setVisible(false);
    jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed
    // Funcion al boton de Cervantes
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    ImageIcon img = new ImageIcon("Cervantes (1).png");
    jLabel4.setIcon(img);
    jPanel1.setVisible(false);
    jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed
    // Funcion al boton de Fundacion
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    ImageIcon img = new ImageIcon("Fundacion (1).png");
    jLabel4.setIcon(img);
    jPanel1.setVisible(false);
    jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed
    //Funcion al boton de Oreamuno
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    ImageIcon img = new ImageIcon("Oreamuno (1).png");
    jLabel4.setIcon(img);
    jPanel1.setVisible(false);
    jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed
    //Funcion al boton de Pitahaya
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
    ImageIcon img = new ImageIcon("Pitahaya (1).png");
    jLabel4.setIcon(img);
    jPanel1.setVisible(false);
    jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed
    //Funcion al boton de Tejar
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
    ImageIcon img = new ImageIcon("Tejar (1).png");
    jLabel4.setIcon(img);
    jPanel1.setVisible(false);
    jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed
    //Funcion al boton de Tierra blanca
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
    ImageIcon img = new ImageIcon("Tierra Blanca (1).png");
    jLabel4.setIcon(img);
    jPanel1.setVisible(false);
    jPanel3.setVisible(true); 
    }//GEN-LAST:event_jButton14ActionPerformed
    //Funcion al boton de Tres Rios
    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
    ImageIcon img = new ImageIcon("Tres Rios (1).png");
    jLabel4.setIcon(img);
    jPanel1.setVisible(false);
    jPanel3.setVisible(true); 
    }//GEN-LAST:event_jButton15ActionPerformed
    // Boton Salir
    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
     System.exit(0); // Salirse del programa desde el botòn 
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VentanaInicial.setVisible(false);
        jPanel1.setVisible(false);
        jPanel3.setVisible(false);
        jPanel2.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButtonMostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMostrarMouseEntered
        // TODO add your handling code here:
        ButtonMostrar.setOpaque(true);
    }//GEN-LAST:event_ButtonMostrarMouseEntered

    private void ButtonMostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMostrarMouseExited
        // TODO add your handling code here:
        ButtonMostrar.setOpaque(false);
    }//GEN-LAST:event_ButtonMostrarMouseExited

    private void ButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMostrarActionPerformed
        LabelMapa.paint(LabelMapa.getGraphics());
        cbxSalida.setEnabled(true);

        int MatrizAdyacencia[][] = {
            {0, 1, 0, 1, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0}, // 1
            {1, 0, 1, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0}, // 2
            {0, 1, 0, 0, 0, 1, 0, 0, 0,  0,  0,  0,  0,  1,  0}, // 3
            {1, 0, 0, 0, 1, 1, 0, 0, 0,  0,  0,  0,  0,  0,  0}, // 4
            {0, 0, 0, 1, 0, 1, 1, 1, 0,  0,  0,  0,  0,  0,  0}, // 5
            {0, 0, 1, 1, 1, 0, 1, 0, 0,  0,  0,  0,  0,  1,  0}, // 6
            {0, 0, 0, 0, 1, 1, 0, 1, 1,  1,  0,  0,  0,  0,  0}, // 7
            {0, 0, 0, 0, 1, 0, 1, 0, 0,  0,  0,  1,  0,  0,  0}, // 8
            {0, 0, 0, 0, 0, 0, 1, 0, 0,  1,  0,  0,  1,  1,  0}, // 9
            {0, 0, 0, 0, 0, 0, 1, 0, 1,  0,  1,  0,  1,  0,  0}, // 10
            {0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  0,  1,  0,  0,  0}, // 11
            {0, 0, 0, 0, 0, 0, 0, 1, 0,  0,  1,  0,  1,  0,  1}, // 12
            {0, 0, 0, 0, 0, 0, 0, 0, 1,  1,  0,  1,  0,  1,  0}, // 13
            {0, 0, 1, 0, 0, 1, 0, 0, 1,  0,  0,  0,  1,  0,  0}, // 14
            {0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  1,  0,  0,  0}  // 15
        };

        double distancias[][] = {
            {0, 8.9, 0, 18.5, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0},
            {8.9, 0, 9.2, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,  0,  0},
            {0, 9.2, 0, 0, 0, 5.8, 0, 0, 0,  0,  0,  0,  0,  12.8,  0},
            {18.5, 0, 0, 0, 13.1, 17.9, 0, 0, 0,  0,  0,  0,  0,  0,  0},
            {0, 0, 0, 13.1, 0, 7.8, 8.4, 8.6, 0,  0,  0,  0,  0,  0,  0},
            {0, 0, 5.8, 17.9, 7.8, 0, 3.5, 0, 0,  0,  0,  0,  0,  13.3,  0},
            {0, 0, 0, 0, 8.4, 3.5, 0, 7.1, 4.7,  5,  0,  0,  0,  0,  0},
            {0, 0, 0, 0, 8.6, 0, 7.1, 0, 0,  0,  0,  15.1,  0,  0,  0},
            {0, 0, 0, 0, 0, 0, 4.7, 0, 0,  1.4,  0,  0,  10.4,  5.8,  0},
            {0, 0, 0, 0, 0, 0, 5, 0, 1.4,  0,  2.1,  0,  10,  0,  0},
            {0, 0, 0, 0, 0, 0, 0, 0, 0,  2.1,  0,  2.5,  0,  0,  0},
            {0, 0, 0, 0, 0, 0, 0, 15.1, 0,  0,  2.5,  0,  10.1,  0,  1.2},
            {0, 0, 0, 0, 0, 0, 0, 0, 10.4,  9.8,  0,  10.1,  0,  12.5,  0},
            {0, 0, 12.8, 0, 0, 13.3, 0, 0, 5.8,  0,  0,  0,  12.5,  0,  0},
            {0, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  1.2,  0,  0,  0}};         // 15

        int coordenadasX[] = {890, 710, 570, 800, 570, 480, 400, 470, 320, 235, 280,  200,  60,  350,  190};
        int coordenadasY[] = {95,  135, 170, 300, 370, 260, 280, 480, 215, 240, 290,  280,  135,  85,  335};
        String nom[] =  {"Turrialba", "Juan Viñas", "Cervantes", "Tucurrique", "Cachí", "Birrisito", "Paraiso", "Orosi", "Oreamuno", "Cartago", "Pitahaya", "Tejar", "Tres Ríos", "Tierra Blanca", "La Fundacion"};

        for (int j = 0; j < 15; j++) {
            datosGraficos.setCoordeX(j, coordenadasX[j]);
            datosGraficos.setCoordeY(j, coordenadasY[j]);
            datosGraficos.setNombre(j, nom[j]);

        }
        for (int j = 0; j < 15; j++) {
            for (int k = 0; k < 15; k++) {
                datosGraficos.setmAdyacencia(j, k, MatrizAdyacencia[j][k]);
                datosGraficos.setmDistancias(j, k, distancias[j][k]);
            }
        }
        NumVertices = 15;
        try {
            PintarRutas(NumVertices, datosGraficos);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonMostrarActionPerformed

    private void TrzarRutaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrzarRutaMouseEntered
        // TODO add your handling code here:
        TrzarRuta.setOpaque(true);
    }//GEN-LAST:event_TrzarRutaMouseEntered

    private void TrzarRutaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrzarRutaMouseExited
        // TODO add your handling code here:
        TrzarRuta.setOpaque(false);
    }//GEN-LAST:event_TrzarRutaMouseExited

    private void TrzarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrzarRutaActionPerformed

        int origen = 0, destino = 0, retrasos = 0;
        String nombreOrigen, nombreDestino, nombreRetrasos;
        nombreOrigen = (String) cbxSalida.getSelectedItem();
        nombreDestino = (String) cbxDestino.getSelectedItem();
        nombreRetrasos = (String) cbxRetrasos.getSelectedItem();

        if ("Turrialba".equals(nombreOrigen)) {
            origen = 0;
        }
        if ("Juan Viñas".equals(nombreOrigen)) {
            origen = 1;
        }
        if ("Cervantes".equals(nombreOrigen)) {
            origen = 2;
        }
        if ("Tucurrique".equals(nombreOrigen)) {
            origen = 3;
        }
        if ("Cachi".equals(nombreOrigen)) {
            origen = 4;
        }
        if ("Birrisito".equals(nombreOrigen)) {
            origen = 5;
        }
        if ("Paraiso".equals(nombreOrigen)) {
            origen = 6;
        }
        if ("Orosi".equals(nombreOrigen)) {
            origen = 7;
        }
        if ("Oreamuno".equals(nombreOrigen)) {
            origen = 8;
        }
        if ("Cartago".equals(nombreOrigen)) {
            origen = 9;
        }
        if ("Pitahaya".equals(nombreOrigen)) {
            origen = 10;
        }
        if ("El Tejar".equals(nombreOrigen)) {
            origen = 11;
        }
        if ("Tres Rios".equals(nombreOrigen)) {
            origen = 12;
        }
        if ("Tierra Blanca".equals(nombreOrigen)) {
            origen = 13;
        }
        if ("La Fundacion".equals(nombreOrigen)) {
            origen = 14;
        }

        /*************************************/

        if ("Turrialba".equals(nombreDestino)) {
            destino = 0;
        }
        if ("Juan Viñas".equals(nombreDestino)) {
            destino = 1;
        }
        if ("Cervantes".equals(nombreDestino)) {
            destino = 2;
        }
        if ("Tucurrique".equals(nombreDestino)) {
            destino = 3;
        }
        if ("Cachi".equals(nombreDestino)) {
            destino = 4;
        }
        if ("Birrisito".equals(nombreDestino)) {
            destino = 5;
        }
        if ("Paraiso".equals(nombreDestino)) {
            destino = 6;
        }
        if ("Orosi".equals(nombreDestino)) {
            destino = 7;
        }
        if ("Oreamuno".equals(nombreDestino)) {
            destino = 8;
        }
        if ("Cartago".equals(nombreDestino)) {
            destino = 9;
        }
        if ("Pitahaya".equals(nombreDestino)) {
            destino = 10;
        }
        if ("El Tejar".equals(nombreDestino)) {
            destino = 11;
        }
        if ("Tres Rios".equals(nombreDestino)) {
            destino = 12;
        }
        if ("Tierra Blanca".equals(nombreDestino)) {
            destino = 13;
        }
        if ("La Fundacion".equals(nombreDestino)) {
            destino = 14;
        }
        //Presa, Semaforo, Choque, Accidente, Animales en la carretera, Derrumbe
        //combobox de tiempo de retrasos
        if ("Presa".equals(nombreRetrasos)) {
            retrasos = 15;
        }
        if ("Semaforo".equals(nombreRetrasos)) {
            retrasos = 3;
        }
        if ("Choque".equals(nombreRetrasos)) {
            retrasos = 20;
        }
        if ("Accidente".equals(nombreRetrasos)) {
            retrasos = 40;
        }
        if ("Animales en la carretera".equals(nombreRetrasos)) {
            retrasos = 10;
        }
        if ("Derrumbe".equals(nombreRetrasos)) {
            retrasos = 25;
        }

        //Se hacen visibles los camos
        jPTiempos.setVisible(true);

        if (origen == destino) {
            Font fuente = new Font("Arial", Font.BOLD, 18);
            JOptionPane.showMessageDialog(null, "Estás en:" + nombreOrigen+"!");

            jPTiempos.setVisible(false);

        } else {
            AlgoritmoDijkstra Dijkstra = new AlgoritmoDijkstra(datosGraficos, NumVertices, origen, destino);
            try {
                Dijkstra.dijkstra();
            } catch (IOException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }

            Font fuente = new Font("Arial", Font.BOLD, 18);

            txtTiempo.setText(Dijkstra.getAcumulado() + " MIN"+" ");
            txtTestimado.setText( Dijkstra.getAcumulado()+ retrasos+ " MIN"+" ");
        }
    }//GEN-LAST:event_TrzarRutaActionPerformed

    private void cbxSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSalidaActionPerformed
        cbxDestino.setEnabled(true);
    }//GEN-LAST:event_cbxSalidaActionPerformed

    private void cbxDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDestinoActionPerformed
        TrzarRuta.setEnabled(true);
        cbxRetrasos.setEnabled(true);
    }//GEN-LAST:event_cbxDestinoActionPerformed

    // Dibuja lineas que representan las rutas posibles que el usuario puede escorer
    public static void PintarRutas(int numVertices, DatosGraficos arboles) throws IOException {// pinta todas las rutas en el mapa a escoger
        for (int j = 0; j < numVertices; j++) {
            for (int k = 0; k < numVertices; k++) {
                if (arboles.getmAdyacencia(j, k) == 1) { //se pinta las líneas
                    Dibujos.pinta_Rutas(LabelMapa.getGraphics(), arboles.getCoordeX(j), arboles.getCoordeY(j), arboles.getCoordeX(k), arboles.getCoordeY(k), arboles.getmDistancias(j, k));
                }
            }
        }
        for (int j = 0; j < numVertices; j++) { // se pintan los simbolos de ubicación en cada lugar
            Dibujos.pinta_localizador(LabelMapa.getGraphics(), arboles.getCoordeX(j), arboles.getCoordeY(j), arboles.getNombre(j));
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonMostrar;
    public static javax.swing.JLabel LabelMapa;
    private javax.swing.JButton TrzarRuta;
    private javax.swing.JPanel VentanaInicial;
    private javax.swing.JComboBox<String> cbxDestino;
    public javax.swing.JComboBox<String> cbxRetrasos;
    private javax.swing.JComboBox<String> cbxSalida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private static javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPTiempos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel tituloConretraso;
    private javax.swing.JLabel tituloSinretraso;
    private javax.swing.JLabel txtTestimado;
    private javax.swing.JLabel txtTiempo;
    // End of variables declaration//GEN-END:variables
}
